# Homebrew cask for the signed, notarized installer published with each release.
#
# Generated by `make cask` from the package that was actually built, so the
# version, the file name and the checksum cannot drift from what is on the
# release. Edit scripts/cask.sh rather than this file.
cask "deadlocker" do
  version "0.1.0"
  sha256 "6f382da56b69684ebe66383022d0477b560f28cf95a7eff297fb3c364d95362a"

  url "https://github.com/JNK/deadlocker/releases/download/v#{version}/Deadlocker-v#{version}.pkg",
      verified: "github.com/JNK/deadlocker/"
  name "Deadlocker"
  desc "MySQL lock playground: provoke a deadlock and read the locks that caused it"
  homepage "https://github.com/JNK/deadlocker"

  # A bare symbol means "this version or newer"; the string comparison form is
  # deprecated.
  depends_on macos: :big_sur

  pkg "Deadlocker-v#{version}.pkg"

  # The installer writes one file into the home directory and registers a
  # receipt; both go when the cask is removed.
  uninstall pkgutil: "io.jnk.deadlocker.*",
            delete:  "#{Dir.home}/.local/bin/deadlocker"

  # The package installs into ~/.local/bin, which is not on the default PATH.
  # Linking it into Homebrew's own bin is what makes `deadlocker` simply work
  # after `brew install`.
  binary "#{Dir.home}/.local/bin/deadlocker"

  zap trash: "#{Dir.home}/.config/deadlocker"

  caveats <<~EOS
    Deadlocker starts its own MySQL containers, so Docker must be running.

      deadlocker            serves the UI on http://127.0.0.1:8899
      deadlocker run        runs every scenario headless
      deadlocker help       everything else

    Configuration lives in ~/.config/deadlocker.
  EOS
end
