# Homebrew formula for the command-line tool.
#
# A formula rather than a cask on the .pkg: Homebrew installs packages with
# `sudo installer -target /`, and the .pkg is deliberately a per-user install
# that needs no administrator password. Asking for one to install something
# into your own home directory is the wrong trade, so brew builds it instead.
# The signed, notarized .pkg is still on every release for anyone who would
# rather double-click one.
#
# Generated by `make formula` from the tag that was published, so the version
# and the checksum cannot drift from the release.
class Deadlocker < Formula
  desc "MySQL lock playground: provoke a deadlock and read the locks that caused it"
  homepage "https://github.com/JNK/deadlocker"
  url "https://github.com/JNK/deadlocker/archive/refs/tags/v0.1.1.tar.gz"
  version "0.1.1"
  sha256 "97061d6aa72ce2a09111cfea6ad8abc6ab3f54f2d3f17b9fd2349f37625b2160"

  depends_on "go" => :build

  def install
    # -trimpath keeps the build machine's absolute paths out of the binary.
    system "go", "build", "-trimpath", "-o", bin/"deadlocker", "./cmd/deadlocker"
  end

  def caveats
    <<~EOS
      Deadlocker starts its own MySQL containers, so Docker must be running.

        deadlocker            serves the UI on http://127.0.0.1:8899
        deadlocker run        runs every scenario headless
        deadlocker help       everything else

      Configuration lives in ~/.config/deadlocker.
    EOS
  end

  test do
    # `help` exercises the binary without needing Docker, which the test
    # sandbox does not have.
    assert_match "serve the web UI", shell_output("#{bin}/deadlocker help 2>&1")
  end
end
